# 网站标题，会显示在浏览器的标签页上
title: 你的网站标题

# 网站的简短描述，有助于搜索引擎了解你的网站
description: 关于我的个人主页、博客和项目。

# 这是最关键的一步：选择一个主题
# 你可以从 GitHub 支持的主题中选择一个，例如 minimal, cayman, midnight 等
# 更多主题请查看官方列表: https://pages.github.com/themes/
theme: jekyll-theme-minimal
